import { Texts } from './types';

export const TEXTS: { [key: string]: Texts } = {
  vi: {
    title: "AI MyProduct",
    author: "By DangLong",
    uploadPlaceholder: "Tải tệp lên hoặc kéo và thả",
    portraitLabel: "Ảnh nhân vật (tùy chọn)",
    fashionItemsLabel: "Ảnh sản phẩm",
    sceneObjectLabel: "Ảnh Bối cảnh / Vật thể (tùy chọn)",
    promptLabel: "Mô tả ý tưởng của bạn",
    promptPlaceholderFashion: "người mẫu sử dụng sản phẩm này, đi dạo trên đường phố Paris",
    qualityLabel: "Chất lượng",
    generateButton: "Tạo ảnh",
    downloadAllButton: "Tải xuống tất cả",
    loadingMessage: "AI đang sáng tạo, vui lòng chờ trong giây lát...",
    resultsGridTitle: "Kết quả",
    fileTooLarge: "Lỗi: Tệp quá lớn (tối đa 10MB).",
    fileTypeInvalid: "Lỗi: Chỉ chấp nhận tệp PNG hoặc JPG.",
    missingInfoFashion: "Vui lòng tải lên ảnh sản phẩm và nhập mô tả.",
    missingInfoSuggestionFashion: "Vui lòng tải lên ảnh sản phẩm để lấy gợi ý.",
    generationError: "Đã xảy ra lỗi khi tạo ảnh. Vui lòng thử lại.",
    english: "English",
    vietnamese: "Tiếng Việt",
    fashionMode: "Tạo ảnh Thời trang",
    contactButton: "Hướng dẫn tạo Sora 2 Free",
    communityButton: "Cộng đồng",
    quotaExceeded: "Lỗi: Bạn đã vượt quá hạn mức sử dụng. Vui lòng kiểm tra gói dịch vụ và chi tiết thanh toán của bạn.",
    zaloButton: "Cộng đồng tạo ảnh KOL ai",
    getSuggestionButton: "✨ Lấy gợi ý",
    gettingSuggestion: "Đang lấy gợi ý...",
    keepFaceLabel: "Giữ lại khuôn mặt tuyệt đối",
    initialStateTitle: "Kết quả của bạn sẽ xuất hiện ở đây",
    initialStateMessage: "Bắt đầu bằng cách tải lên hình ảnh và mô tả ý tưởng của bạn.",
    addFashionRowButton: 'THÊM +..',
    generateAllButton: 'Tạo tất cả ảnh',
    removeRowButton: 'Xóa',
    reuseButton: 'Sử dụng lại',
    promptPlaceholder: 'ví dụ: ảnh chân dung chuyên nghiệp cho hồ sơ LinkedIn',
    promptPlaceholderCreative: 'ví dụ: chân dung siêu thực với nền thiên hà',
    referenceImageLabelCreative: 'Ảnh tham khảo',
    referenceImageLabel: 'Ảnh tham khảo (Sản phẩm, Phong cách, v.v.)',
    analyzingImage: 'Đang phân tích ảnh...',
    communityShowcaseTitle: 'Góc Cộng Đồng',
    creativeMode: 'Chế độ Sáng tạo',
    brandMode: 'Chế độ Thương hiệu',

    // Outfit Processing Mode
    outfitProcessingMode: 'Xử lý ảnh Outfit',
    originalImageLabel: 'Ảnh nhân vật',
    resultLabel: 'Kết Quả',
    addOutfitRowButton: 'thêm ảnh ++',
    processAllButton: 'Xử lý tất cả',
    processButton: 'Tạo ảnh Outfit',
    missingInfoOutfit: 'Vui lòng tải ảnh trang phục chính để xử lý.',
    viewButton: 'Xem ảnh',
    fashionItemsLabelOutfit: 'Ảnh sản phẩm & Phụ kiện',
    addAccessoryButton: 'Thêm phụ kiện',

    // Title/Description Generation
    generatedTitleLabel: "Tiêu đề",
    generatedDescriptionLabel: "Mô tả & Hashtags",
    copyButtonLabel: "Sao chép",
    copiedLabel: "Đã chép!",
    socialContentTitle: "Nội dung Social",
    generatedVeoPromptLabel: "Prompt Chuyển động gợi ý",

    // Regeneration
    regenerateButton: "Tạo lại ảnh này",
    editPromptTitle: "Chỉnh sửa mô tả",
    removeFaceButtonLabel: "Xóa mặt",
    removePersonButtonLabel: "Xóa người",
  },
  en: {
    title: "AI MyProduct",
    author: "By DangLong",
    uploadPlaceholder: "Upload a file or drag and drop",
    portraitLabel: "Character Image (Optional)",
    fashionItemsLabel: "Product Image",
    sceneObjectLabel: "Scene / Object Image (Optional)",
    promptLabel: "Custom Prompt",
    promptPlaceholderFashion: "the model using this product, walking on a street in Paris",
    qualityLabel: "Quality",
    generateButton: "Generate Images",
    downloadAllButton: "Download All",
    loadingMessage: "AI is creating, please wait a moment...",
    resultsGridTitle: "Results",
    fileTooLarge: "Error: File is too large (max 10MB).",
    fileTypeInvalid: "Error: Only PNG or JPG files are accepted.",
    missingInfoFashion: "Please upload a product image and enter a prompt.",
    missingInfoSuggestionFashion: "Please upload a product image to get a suggestion.",
    generationError: "An error occurred while generating images. Please try again.",
    english: "English",
    vietnamese: "Vietnamese",
    fashionMode: "Fashion Image Generation",
    contactButton: "Guide to Create Sora 2 Free",
    communityButton: "Community",
    quotaExceeded: "Error: You have exceeded your quota. Please check your plan and billing details.",
    zaloButton: "KOL AI Image Community",
    getSuggestionButton: "✨ Get Suggestion",
    gettingSuggestion: "Getting suggestion...",
    keepFaceLabel: "Absolutely Preserve Face",
    initialStateTitle: "Your results will appear here",
    initialStateMessage: "Get started by uploading your images and describing your idea.",
    addFashionRowButton: 'ADD +..',
    generateAllButton: 'Generate All',
    removeRowButton: 'Remove',
    reuseButton: 'Reuse',
    promptPlaceholder: 'e.g., a professional headshot for a LinkedIn profile',
    promptPlaceholderCreative: 'e.g., a surreal portrait with galaxy background',
    referenceImageLabelCreative: 'Reference Image',
    referenceImageLabel: 'Reference Image (Product, Style, etc.)',
    analyzingImage: 'Analyzing image...',
    communityShowcaseTitle: 'Community Showcase',
    creativeMode: 'Creative Mode',
    brandMode: 'Brand Mode',
    
    // Outfit Processing Mode
    outfitProcessingMode: 'Outfit Image Processing',
    originalImageLabel: 'Character Image',
    resultLabel: 'Result',
    addOutfitRowButton: 'Add Image ++',
    processAllButton: 'Process All',
    processButton: 'Compose Outfit',
    missingInfoOutfit: 'Please upload the main outfit item to process.',
    viewButton: 'View Image',
    fashionItemsLabelOutfit: 'Product & Accessories Image',
    addAccessoryButton: 'Add Accessory',

    // Title/Description Generation
    generatedTitleLabel: "Title",
    generatedDescriptionLabel: "Description & Hashtags",
    copyButtonLabel: "Copy",
    copiedLabel: "Copied!",
    socialContentTitle: "Social Content",
    generatedVeoPromptLabel: "Suggested Motion Prompt",

    // Regeneration
    regenerateButton: "Regenerate This Image",
    editPromptTitle: "Edit Prompt",
    removeFaceButtonLabel: "Remove Face",
    removePersonButtonLabel: "Remove Person",
  }
};

export const COMMUNITY_URL = "https://www.facebook.com/share/g/19sjc5ttTA/";
export const ZALO_URL = "https://zalo.me/g/dndikz801";
export const SORA_GUIDE_URL = "https://youtu.be/PbEiJs5glfs";